# Generated by Django 3.2 on 2021-04-07 15:32

from django.conf import settings
from django.db import migrations, models
import scheduler_schema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(validators=[scheduler_schema.models.validate_datetime])),
                ('title', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='scheduled_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
