# Generated by Django 3.2 on 2021-04-08 04:02

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import scheduler_schema.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scheduler_schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailibility',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='date_time',
            new_name='start_date_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[scheduler_schema.models.validate_datetime]),
            preserve_default=False,
        ),
    ]
